# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_recepta', models.CharField(max_length=16)),
                ('data_creacio', models.DateField()),
                ('descripcio', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=300)),
                ('procediment', models.CharField(max_length=2000)),
                ('vots', models.IntegerField()),
                ('imatge', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('cognom', models.CharField(max_length=50)),
                ('datanaixament', models.DateField()),
                ('sexe', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recepta',
            name='nom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quecuino.Usuari'),
        ),
    ]
