# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quecuino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepta',
            name='slug',
            field=models.SlugField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
