# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quecuino', '0002_auto_20190208_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepta',
            name='nom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
