# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quecuino', '0002_recepta_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepta',
            name='votsenumero',
            field=models.IntegerField(default=0),
        ),
    ]
