# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quecuino', '0004_auto_20190209_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepta',
            name='imatge',
        ),
    ]
