# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quecuino', '0005_remove_recepta_imatge'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepta',
            name='imatge',
            field=models.ImageField(default='', upload_to='Images'),
            preserve_default=False,
        ),
    ]
