# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quecuino', '0007_auto_20190209_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepta',
            old_name='nom_user',
            new_name='usuario',
        ),
    ]
