# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quecuino', '0011_auto_20190209_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuari',
            name='sexe',
        ),
    ]
